main:
  project_name: Deploying a Machine Learning Model on Heroku with FastAPI
  experiment_name: development
  steps: all

data:
  cat_features: [
        "workclass",
        "education",
        "marital-status",
        "occupation",
        "relationship",
        "race",
        "sex",
        "native-country",
    ]